### ISSUE TITLE
Logger unexpectedly displays an error in DnsUdpClient

### ISSUE THREAD

**Issue by SamLowryMOI** [alanedwardes/Ae.Dns#15]
If you are using DnsUdpClient with a logger,
```
[... Create any logger...]
using IDnsClient dnsClient = DnsUdpClient(logger, Options.Create((DnsUdpClientOptions)IPAddress.Parse("1.1.1.1")));
DnsMessage answer = await dnsClient.Query(DnsQueryFactory.CreateQuery("google.com"), CancellationToken.None);
```

the logger unexpectedly displays an error when calling ```Query```:

```
crit: Ae.Dns.Client.DnsUdpClient[0]
      Received bad network response
System.Net.Sockets.SocketException (10022): An invalid argument was supplied
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Ae.Dns.Protocol.SocketTaskExtensions.<>c.<ReceiveAsync>b__2_0(ArraySegment`1 targetBuffer, SocketFlags flags, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at Ae.Dns.Protocol.SocketTaskExtensions.ReceiveAsync(Socket socket, ArraySegment`1 buffer, SocketFlags socketFlags)
   at Ae.Dns.Protocol.SocketTaskExtensions.ReceiveAsync(Socket socket, ArraySegment`1 buffer, SocketFlags socketFlags, CancellationToken token)
   at Ae.Dns.Client.DnsUdpClient.ReceiveTask()
RES: 13328 Domain: google.com Type: A Class: IN Response: NoError
Answers: 6
 * Name: google.com Type: A Class: IN TTL: 122 Resource: 108.177.15.138
 * Name: google.com Type: A Class: IN TTL: 122 Resource: 108.177.15.102
 * Name: google.com Type: A Class: IN TTL: 122 Resource: 108.177.15.100
 * Name: google.com Type: A Class: IN TTL: 122 Resource: 108.177.15.139
 * Name: google.com Type: A Class: IN TTL: 122 Resource: 108.177.15.113
 * Name: google.com Type: A Class: IN TTL: 122 Resource: 108.177.15.101
```

BTW, what will happen with ILogger, will they be removed in the different DnsClients or will they stay?

**Comment by alanedwardes** [comment]
To address the ILogger point - I'm not intending to remove those from the API, and I don't think this is related to the problem you're seeing (it just surfaces it).

I remember seeing this under `netcoreapp2.1` consistently, and I remember it being related to calling `Socket.BeginReceive` before sending anything into it. But, it didn't seem to affect other runtimes (I assumed it was a problem that Microsoft fixed later).

Is this cusing problems, or just creating noise?

**Comment by SamLowryMOI** [comment]
That was just meant as info to you, I wouldn't use it anyway. In Powershell you get 100+ messages with one query.

**Comment by alanedwardes** [comment]
I have added a change to address this for NETSTANDARD2_0 only: https://github.com/alanedwardes/Ae.Dns/pull/18
